//* Component Data ==============================
// This is the master list - update status here as you work!

//* Types ==============================

export type Status = '🟢' | '🟡' | '🔴' | '⚪'
export type Tier = 'core' | 'legacy' | 'webgpu' | 'external' | 'experimental'

export interface ComponentEntry {
  name: string
  tier: Tier
  category: string
  examplePath: string // Path to demo in examples/src/demos/
  structure: Status
  imports: Status
  types: Status
  example: Status
  tests: Status
  tslConversion?: Status // Only for webgpu tier
  notes: string
}

export const components: ComponentEntry[] = [
  //* CORE - Cameras (3) ==============================
  {
    name: 'OrthographicCamera',
    tier: 'core',
    category: 'Cameras',
    examplePath: '/core/cameras/orthographic',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🟢',
    tests: '🔴',
    notes: 'Example created',
  },
  {
    name: 'PerspectiveCamera',
    tier: 'core',
    category: 'Cameras',
    examplePath: '/core/cameras/perspective',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🟢',
    tests: '🔴',
    notes: 'Example created',
  },
  {
    name: 'useCustomRaycast',
    tier: 'core',
    category: 'Cameras',
    examplePath: '/core/cameras/usecustomraycast',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Controls (18) ==============================
  {
    name: 'ArcballControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/arcball',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'DeviceOrientationControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/deviceorientation',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'DragControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/drag',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'FaceControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/face',
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Cross-tier imports',
  },
  {
    name: 'FirstPersonControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/firstperson',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'FlyControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/fly',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'KeyboardControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/keyboard',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'MapControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/map',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'MotionPathControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/motionpath',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'OrbitControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/orbit',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🟢',
    tests: '🔴',
    notes: 'Example created',
  },
  {
    name: 'PointerLockControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/pointerlock',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'PresentationControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/presentation',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'ScrollControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/scroll',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'Select',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/select',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'TrackballControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/trackball',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'TransformControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/transform',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'GizmoHelper',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/gizmohelper',
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Case sensitivity, cross-tier',
  },
  {
    name: 'GizmoViewport',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/gizmoviewport',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'GizmoViewcube',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/gizmoviewcube',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'PivotControls',
    tier: 'core',
    category: 'Controls',
    examplePath: '/core/controls/pivot',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: 'Multi-file component',
  },

  //* CORE - Staging (17) ==============================
  {
    name: 'Backdrop',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/backdrop',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'BBAnchor',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/bbanchor',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Bounds',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/bounds',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Center',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/center',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Environment',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/environment',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Float',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/float',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Grid',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/grid',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Lightformer',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/lightformer',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Resize',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/resize',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'ScreenSizer',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/screensizer',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Shadow',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/shadow',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Sky',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/sky',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'SpotLight',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/spotlight',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Stage',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/stage',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Stars',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/stars',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useBoxProjectedEnv',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/useboxprojectedenv',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useEnvironment',
    tier: 'core',
    category: 'Staging',
    examplePath: '/core/staging/useenvironment',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Geometry (15) ==============================
  {
    name: 'CatmullRomLine',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/catmullromline',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'CubicBezierLine',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/cubicbezierline',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'CurveModifier',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/curvemodifier',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Decal',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/decal',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Detailed',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/detailed',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Edges',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/edges',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'Line',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/line',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Points',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/points',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'QuadraticBezierLine',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/quadraticbezierline',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'RoundedBox',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/roundedbox',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'ScreenQuad',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/screenquad',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Segments',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/segments',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Text3D',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/text3d',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Trail',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/trail',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Wireframe',
    tier: 'core',
    category: 'Geometry',
    examplePath: '/core/geometry/wireframe',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Abstractions (9) ==============================
  {
    name: 'AsciiRenderer',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/asciirenderer',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Billboard',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/billboard',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Clone',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/clone',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'ComputedAttribute',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/computedattribute',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Unused @ts-expect-error',
  },
  {
    name: 'Example',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/example',
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Cross-component imports',
  },
  {
    name: 'Instances',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/instances',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'Sampler',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/sampler',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'ScreenSpace',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/screenspace',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Svg',
    tier: 'core',
    category: 'Abstractions',
    examplePath: '/core/abstractions/svg',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Performance (7) ==============================
  {
    name: 'AdaptiveDpr',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/adaptivedpr',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'AdaptiveEvents',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/adaptiveevents',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'DetectGPU',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/detectgpu',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'meshBounds',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/meshbounds',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'PerformanceMonitor',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/performancemonitor',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Stats',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/stats',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'StatsGl',
    tier: 'core',
    category: 'Performance',
    examplePath: '/core/performance/statsgl',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Loaders (15) ==============================
  {
    name: 'CubeTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/cubetexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Loader',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/loader',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'MatcapTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/matcaptexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Preload',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/preload',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'ScreenVideoTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/screenvideotexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'TrailTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/trailtexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useFBX',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/usefbx',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useFont',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/usefont',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useGLTF',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/usegltf',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useKTX2',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/usektx2',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useProgress',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/useprogress',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useSpriteLoader',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/usespriteloader',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/usetexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'VideoTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/videotexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'WebcamVideoTexture',
    tier: 'core',
    category: 'Loaders',
    examplePath: '/core/loaders/webcamvideotexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Helpers (12) ==============================
  {
    name: 'CycleRaycast',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/cycleraycast',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Html',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/html',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'PointMaterial',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/pointmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'PositionalAudio',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/positionalaudio',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'SpriteAnimator',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/spriteanimator',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Text',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/text',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useAnimations',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/useanimations',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useAspect',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/useaspect',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useContextBridge',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/usecontextbridge',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useCursor',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/usecursor',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useHelper',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/usehelper',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'useIntersect',
    tier: 'core',
    category: 'Helpers',
    examplePath: '/core/helpers/useintersect',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Portal (3) ==============================
  {
    name: 'Fisheye',
    tier: 'core',
    category: 'Portal',
    examplePath: '/core/portal/fisheye',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Mask',
    tier: 'core',
    category: 'Portal',
    examplePath: '/core/portal/mask',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'View',
    tier: 'core',
    category: 'Portal',
    examplePath: '/core/portal/view',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* CORE - Effects (3) ==============================
  {
    name: 'CameraShake',
    tier: 'core',
    category: 'Effects',
    examplePath: '/core/effects/camerashake',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import issue',
  },
  {
    name: 'Cloud',
    tier: 'core',
    category: 'Effects',
    examplePath: '/core/effects/cloud',
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Cross-component imports',
  },
  {
    name: 'Sparkles',
    tier: 'core',
    category: 'Effects',
    examplePath: '/core/effects/sparkles',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* EXTERNAL (6) ==============================
  {
    name: 'Bvh',
    tier: 'external',
    category: 'External',
    examplePath: '/external/bvh',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'CameraControls',
    tier: 'external',
    category: 'External',
    examplePath: '/external/cameracontrols',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Facemesh',
    tier: 'external',
    category: 'External',
    examplePath: '/external/facemesh',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'FaceLandmarker',
    tier: 'external',
    category: 'External',
    examplePath: '/external/facelandmarker',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'NormalTexture',
    tier: 'external',
    category: 'External',
    examplePath: '/external/normaltexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'Splat',
    tier: 'external',
    category: 'External',
    examplePath: '/external/splat',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },

  //* EXPERIMENTAL (1) ==============================
  {
    name: 'MarchingCubes',
    tier: 'experimental',
    category: 'Experimental',
    examplePath: '/experimental/marchingcubes',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Utils import, type issues',
  },

  //* LEGACY - Helpers (1) ==============================
  {
    name: 'Fbo / useFBO',
    tier: 'legacy',
    category: 'Helpers',
    examplePath: '/legacy/helpers/fbo',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: 'WebGL-specific',
  },

  //* LEGACY - Portal (3) ==============================
  {
    name: 'Hud',
    tier: 'legacy',
    category: 'Portal',
    examplePath: '/legacy/portal/hud',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: 'WebGL render targets',
  },
  {
    name: 'RenderCubeTexture',
    tier: 'legacy',
    category: 'Portal',
    examplePath: '/legacy/portal/rendercubetexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'RenderTexture',
    tier: 'legacy',
    category: 'Portal',
    examplePath: '/legacy/portal/rendertexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },

  //* LEGACY - Cameras (1) ==============================
  {
    name: 'CubeCamera',
    tier: 'legacy',
    category: 'Cameras',
    examplePath: '/legacy/cameras/cubecamera',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: 'WebGL-specific',
  },

  //* LEGACY - Abstractions (1) ==============================
  {
    name: 'Effects',
    tier: 'legacy',
    category: 'Abstractions',
    examplePath: '/legacy/abstractions/effects',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },

  //* LEGACY - Materials (21) ==============================
  {
    name: 'AccumulativeShadows',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/accumulativeshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'BakeShadows',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/bakeshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'BlurPass',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/blurpass',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'Caustics',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/caustics',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'ContactShadows',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/contactshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'ConvolutionMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/convolutionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'DiscardMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/discardmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'GradientTexture',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/gradienttexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'Image',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/image',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'MeshDiscardMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshdiscardmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'MeshDistortMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshdistortmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'MeshPortalMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshportalmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'MeshReflectorMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshreflectormaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'MeshRefractionMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshrefractionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'MeshTransmissionMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshtransmissionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'MeshWobbleMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/meshwobblematerial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'Outlines',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/outlines',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'shaderMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/shadermaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'SoftShadows',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/softshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    example: '🔴',
    tests: '🔴',
    notes: '',
  },
  {
    name: 'SpotLightMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/spotlightmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },
  {
    name: 'WireframeMaterial',
    tier: 'legacy',
    category: 'Materials',
    examplePath: '/legacy/materials/wireframematerial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    example: '🔴',
    tests: '🔴',
    notes: 'Type issues',
  },

  //* WEBGPU - Materials (21) - All need TSL conversion ==============================
  {
    name: 'AccumulativeShadows',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/accumulativeshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'BakeShadows',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/bakeshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'BlurPass',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/blurpass',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'Caustics',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/caustics',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'ContactShadows',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/contactshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'ConvolutionMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/convolutionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Low priority',
  },
  {
    name: 'DiscardMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/discardmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Low priority',
  },
  {
    name: 'GradientTexture',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/gradienttexture',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'Image',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/image',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'MeshDiscardMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshdiscardmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Low priority',
  },
  {
    name: 'MeshDistortMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshdistortmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'MeshPortalMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshportalmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'MeshReflectorMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshreflectormaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'MeshRefractionMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshrefractionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'MeshTransmissionMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshtransmissionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'MeshWobbleMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/meshwobblematerial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'Outlines',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/outlines',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'shaderMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/shadermaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'High priority',
  },
  {
    name: 'SoftShadows',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/softshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'SpotLightMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/spotlightmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Medium priority',
  },
  {
    name: 'WireframeMaterial',
    tier: 'webgpu',
    category: 'Materials',
    examplePath: '/webgpu/materials/wireframematerial',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Low priority',
  },

  //* WEBGPU - Helpers/Portal/Cameras/Abstractions (6) ==============================
  {
    name: 'Fbo / useFBO',
    tier: 'webgpu',
    category: 'Helpers',
    examplePath: '/webgpu/helpers/fbo',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Needs WebGPU render targets',
  },
  {
    name: 'Hud',
    tier: 'webgpu',
    category: 'Portal',
    examplePath: '/webgpu/portal/hud',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Needs WebGPU render targets',
  },
  {
    name: 'RenderCubeTexture',
    tier: 'webgpu',
    category: 'Portal',
    examplePath: '/webgpu/portal/rendercubetexture',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Needs WebGPU render targets',
  },
  {
    name: 'RenderTexture',
    tier: 'webgpu',
    category: 'Portal',
    examplePath: '/webgpu/portal/rendertexture',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Needs WebGPU render targets',
  },
  {
    name: 'CubeCamera',
    tier: 'webgpu',
    category: 'Cameras',
    examplePath: '/webgpu/cameras/cubecamera',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Needs WebGPU render targets',
  },
  {
    name: 'Effects',
    tier: 'webgpu',
    category: 'Abstractions',
    examplePath: '/webgpu/abstractions/effects',
    structure: '🟢',
    imports: '🟢',
    types: '🔴',
    example: '🔴',
    tests: '🔴',
    tslConversion: '🔴',
    notes: 'Needs TSL shader conversion',
  },
]
