//* Native Entry Point ==============================
// AUTO-GENERATED by scripts/generate-native-exports.ts
// Do not edit manually - run: yarn generate:native
//
// This entry exports drei components for React Native with WebGPU aliasing.
// When built, all #three imports resolve to 'three/webgpu'.
//
// Excluded components (12):
//   - Html: requires DOM which is not available on React Native
//   - ArcballControls: requires DOM pointer events not available on React Native
//   - DragControls: requires DOM pointer events not available on React Native
//   - FirstPersonControls: requires DOM pointer events not available on React Native
//   - FlyControls: requires DOM pointer events not available on React Native
//   - KeyboardControls: requires keyboard events not available on React Native
//   - MapControls: requires DOM pointer events not available on React Native
//   - OrbitControls: requires DOM pointer events not available on React Native
//   - PointerLockControls: requires Pointer Lock API not available on React Native
//   - ScrollControls: requires DOM scroll events not available on React Native
//   - TrackballControls: requires DOM pointer events not available on React Native
//   - Caustics: not yet supported on React Native
//
// Usage: import { Box, MeshDistortMaterial } from '@react-three/drei/native'

//* Value exports ==============================
export {
  AccumulativeShadows, AdaptiveDpr, AdaptiveEvents, BBAnchor, Backdrop,
  BakeShadows, Billboard, BlurPass, Bounds, Box,
  CameraShake, Capsule, CatmullRomLine, CausticsMaterial, CausticsNormalMaterial,
  CausticsProjectionMaterial, Center, Circle, Clone, Cloud,
  CloudInstance, Clouds, ComputedAttribute, Cone, ContactShadows,
  ConvolutionMaterial, CubeCamera, CubeTexture, CubicBezierLine, CurveModifier,
  CycleRaycast, Cylinder, Decal, Detailed, DetectGPU,
  DeviceOrientationControls, DiscardMaterial, Dodecahedron, Edges, Environment,
  EnvironmentCube, EnvironmentMap, EnvironmentPortal, Example, Extrude,
  FakeCloudMaterial, Fbo, Fbx, Fisheye, Float,
  GizmoHelper, GizmoViewcube, GizmoViewport, Gltf, GradientTexture,
  GradientType, Grid, Helper, Hud, Icosahedron,
  Image, Instance, InstancedAttribute, Instances, IsObject,
  Ktx2, Lathe, Lightformer, Line, Loader,
  Mask, MatcapTexture, Merged, MeshDistortMaterial, MeshPortalMaterial,
  MeshReflectorMaterial, MeshReflectorMaterialImpl, MeshRefractionMaterial, MeshTransmissionMaterial, MeshWobbleMaterial,
  MotionPathControls, NormalTexture, Octahedron, OrthographicCamera, Outlines,
  PerformanceMonitor, PerspectiveCamera, PivotControls, Plane, Point,
  PointMaterial, PointMaterialImpl, Points, PointsBuffer, Polyhedron,
  PositionMesh, PositionPoint, PositionalAudio, Preload, PresentationControls,
  Progress, QuadraticBezierLine, RandomizedLight, RenderCubeTexture, RenderTexture,
  Resize, Ring, RoundedBox, RoundedBoxGeometry, Sampler,
  ScreenQuad, ScreenSizer, ScreenSpace, ScreenVideoTexture, Scroll,
  Segment, SegmentObject, Segments, Select, Shadow,
  Shape, Sky, SoftShadows, Sparkles, SparklesMaterial,
  Sphere, SpotLight, SpotLightMaterial, SpriteAnimator, Stage,
  StarfieldMaterial, Stars, Stats, StatsGl, Svg,
  Tetrahedron, Text3D, Texture, Torus, TorusKnot,
  Trail, TrailTexture, TransformControls, Tube, VideoTexture,
  View, WebcamVideoTexture, Wireframe, WireframeMaterial, WireframeMaterialShaders,
  accumulativeContext, calcPosFromAngles, checkIfFrameIsEmpty, createInstances, getFirstFrame,
  meshBounds, presetsObj, setBarycentricCoordinates, setWireframeOverride, useAnimations,
  useAspect, useBounds, useContextBridge, useCubeCamera, useCubeTexture,
  useCursor, useCustomRaycast, useDepthBuffer, useDetectGPU, useEnvironment,
  useFBO, useFBX, useFont, useGLTF, useGizmoContext,
  useHelper, useIntersect, useKTX2, useKeyboardControls, useMask,
  useMatcapTexture, useMotion, useNormalTexture, usePerformanceMonitor, useProgress,
  useScroll, useSelect, useSpriteAnimator, useSpriteLoader, useSurfaceSampler,
  useTexture, useTrail, useTrailTexture, useVideoTexture, useWireframeUniforms
} from '../webgpu'

//* Type exports ==============================
export type {
  AccumulativeShadowsProps, Args, BBAnchorProps, BackdropProps, BillboardProps,
  BlurPassProps, BoundsApi, BoundsProps, CalculatePosition, CameraShakeProps,
  CatmullRomLineProps, CenterProps, CloneProps, CloudProps, CloudsProps,
  ComputedAttributeProps, ContactShadowsProps, ContainerProps, CubeCameraOptions, CubeCameraProps,
  CubeTextureProps, CubicBezierLineProps, CurveModifierProps, CurveModifierRef, CycleRaycastProps,
  DecalProps, DetailedProps, DetectGPUProps, DeviceOrientationControlsProps, EdgesProps,
  EnvironmentLoaderProps, EnvironmentProps, ExampleApi, ExampleProps, FboProps,
  FisheyeProps, FloatProps, FontData, FrameData, GizmoHelperProps,
  GltfProps, Glyph, GradientTextureProps, GridMaterialType, GridProps,
  HelperProps, HudProps, ImageProps, InstanceProps, InstancedAttributeProps,
  InstancesProps, KeyboardControlsEntry, LightProps, LineProps, LoaderOptions,
  MaskProps, MergedProps, MeshDistortMaterialProps, MeshReflectorMaterialProps, MeshRefractionMaterialProps,
  MeshRefractionMaterialType, MeshTransmissionMaterialProps, MetaData, MotionPathProps, MotionPathRef,
  OnCenterCallbackProps, OrbitControlsChangeEvent, OrthographicCameraProps, OutlinesProps, PerformanceMonitorApi,
  PerformanceMonitorProps, PerspectiveCameraProps, PivotControlsProps, PointMaterialProps, PointsBuffersProps,
  PointsInstancesProps, PortalProps, PositionalAudioProps, PreloadProps, PresentationControlProps,
  PresetsType, QuadraticBezierLineProps, QuadraticBezierLineRef, RandomizedLightProps, RenderCubeTextureApi,
  RenderCubeTextureProps, RenderTextureProps, ResizeProps, RoundedBoxGeometryProps, RoundedBoxProps,
  SamplerProps, ScreenQuadProps, ScreenSizerProps, ScreenSpaceProps, ScreenVideoTextureProps,
  ScrollControlsState, ScrollProps, SegmentProps, SegmentsProps, SelectProps,
  ShadowProps, ShadowType, ShakeController, ShapeProps, Size,
  SizeProps, SkyProps, SoftShadowsProps, SparklesProps, SpotLightProps,
  SpriteAnimatorProps, SpriteData, StageProps, StarsProps, StatsGlProps,
  StatsProps, SvgProps, Text3DProps, TrailProps, TrailTextureProps,
  TransformControlsProps, TransformFn, VideoTextureProps, ViewProps, ViewportProps,
  WebcamVideoTextureProps, WireframeMaterialProps, WireframeMaterialType, WobbleMaterialProps, useSurfaceSamplerProps
} from '../webgpu'
