//*Simplified Component Registry ==============================
// Single source of truth for all drei components, their demos, and status tracking.
// Each conceptual component has ONE entry, with renderer support tracked via columns.
// doesnt link to the components, meant to be parsed in storybooks

//* Types ==============================

export type Status = 3 | 2 | 1 | '0'

// Renderer support indicates which renderer implementations exist
// - 'universal': Works with any renderer, no shader code needed
// - 'legacy-only': Only WebGL/legacy implementation exists
// - 'webgpu-only': Only WebGPU/TSL implementation exists (rare)
// - 'dual': Has both legacy and WebGPU implementations
export type RendererSupport = 'universal' | 'legacy-only' | 'webgpu-only' | 'dual'

// Categories for grouping - simplified from previous tier system
export type Category =
  | 'Cameras'
  | 'Controls'
  | 'Abstractions'
  | 'Effects'
  | 'Geometry'
  | 'Helpers'
  | 'Loaders'
  | 'Performance'
  | 'Portal'
  | 'Staging'
  | 'UI'
  | 'Materials'
  | 'External'
  | 'Experimental'

export interface DreiComponent {
  // Identity
  name: string
  category: Category
  title: string
  description: string

  // Demo routing - path is always present, component only if demo exists
  path: string
  component?: React.ComponentType

  // Base status tracking (applies to core/universal implementations)
  structure: Status
  imports: Status
  types: Status
  tests: Status
  notes: string

  // Renderer support - determines which columns appear in dashboard
  rendererSupport: RendererSupport

  // Legacy (WebGL) specific status - only for legacy-only or dual
  legacyStatus?: Status

  // WebGPU specific status - only for webgpu-only or dual
  webgpuStatus?: Status
  tslConversion?: Status // TSL shader conversion progress
}

// Legacy Tier type for backward compatibility with sidebar grouping
export type Tier = 'core' | 'external' | 'experimental'

//* Component Registry ==============================
// One entry per conceptual component. Renderer-specific status tracked in columns.

export const components: DreiComponent[] = [
  //* Cameras ==============================
  {
    name: 'OrthographicCamera',
    category: 'Cameras',
    title: 'Orthographic Camera',
    description: 'A camera that uses an orthographic projection.',
    path: '/core/cameras/orthographic',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Example created',
    rendererSupport: 'universal',
  },
  {
    name: 'PerspectiveCamera',
    category: 'Cameras',
    title: 'Perspective Camera',
    description: 'A camera that uses a perspective projection.',
    path: '/core/cameras/perspective',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Example created',
    rendererSupport: 'universal',
  },
  {
    name: 'useCustomRaycast',
    category: 'Cameras',
    title: 'Use Custom Raycast',
    description: 'Hook for custom raycast behavior.',
    path: '/core/cameras/usecustomraycast',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CubeCamera',
    category: 'Cameras',
    title: 'Cube Camera',
    description: 'Camera for rendering cube maps / environment captures.',
    path: '/cameras/cubecamera',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },

  //* Controls ==============================
  {
    name: 'OrbitControls',
    category: 'Controls',
    title: 'Orbit Controls',
    description: 'A control that allows the camera to orbit around the scene.',
    path: '/core/controls/orbit',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Example created',
    rendererSupport: 'universal',
  },
  {
    name: 'ArcballControls',
    category: 'Controls',
    title: 'Arcball Controls',
    description: 'A control that allows the camera to orbit around the scene.',
    path: '/core/controls/arcball',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'MapControls',
    category: 'Controls',
    title: 'Map Controls',
    description: 'A control that allows the camera to move around the scene.',
    path: '/core/controls/map',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'PointerLockControls',
    category: 'Controls',
    title: 'Pointer Lock Controls',
    description: 'A control that allows the camera to lock to the scene.',
    path: '/core/controls/pointerlock',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'TrackballControls',
    category: 'Controls',
    title: 'Trackball Controls',
    description: 'A control that allows the camera to orbit around the scene.',
    path: '/core/controls/trackball',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'FlyControls',
    category: 'Controls',
    title: 'Fly Controls',
    description: 'A control that allows the camera to fly around the scene.',
    path: '/core/controls/fly',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'DeviceOrientationControls',
    category: 'Controls',
    title: 'Device Orientation Controls',
    description: 'Control camera with device orientation (mobile/gyroscope).',
    path: '/core/controls/deviceorientation',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'DragControls',
    category: 'Controls',
    title: 'Drag Controls',
    description: 'Drag objects in the scene with mouse.',
    path: '/core/controls/drag',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'FirstPersonControls',
    category: 'Controls',
    title: 'First Person Controls',
    description: 'First-person shooter style camera controls.',
    path: '/core/controls/firstperson',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'KeyboardControls',
    category: 'Controls',
    title: 'Keyboard Controls',
    description: 'Keyboard input management for scene interactions.',
    path: '/core/controls/keyboard',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PivotControls',
    category: 'Controls',
    title: 'Pivot Controls',
    description: 'Transform gizmo for moving, rotating, and scaling objects.',
    path: '/core/controls/pivot',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Multi-file component',
    rendererSupport: 'universal',
  },
  {
    name: 'TransformControls',
    category: 'Controls',
    title: 'Transform Controls',
    description: 'Three.js TransformControls for precise object manipulation.',
    path: '/core/controls/transform',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'MotionPathControls',
    category: 'Controls',
    title: 'Motion Path Controls',
    description: 'Animate camera along a curved path.',
    path: '/core/controls/motionpath',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PresentationControls',
    category: 'Controls',
    title: 'Presentation Controls',
    description: 'Drag-to-rotate controls ideal for product showcases.',
    path: '/core/controls/presentation',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'FaceControls',
    category: 'Controls',
    title: 'Face Controls',
    description: 'Control camera with face tracking (requires webcam and MediaPipe).',
    path: '/core/controls/face',
    structure: 3,
    imports: 2,
    types: 2,
    tests: 1,
    notes: 'Cross-tier imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Select',
    category: 'Controls',
    title: 'Select',
    description: 'Click and box-select objects in the scene.',
    path: '/core/controls/select',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScrollControls',
    category: 'Controls',
    title: 'Scroll Controls',
    description: 'Create scroll-based animations and interactions.',
    path: '/core/controls/scroll',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'GizmoHelper',
    category: 'Controls',
    title: 'Gizmo Helper',
    description: 'Visual orientation helper showing scene axes.',
    path: '/core/controls/gizmo',
    structure: 3,
    imports: 2,
    types: 2,
    tests: 1,
    notes: 'Case sensitivity, cross-tier',
    rendererSupport: 'universal',
  },
  {
    name: 'GizmoViewport',
    category: 'Controls',
    title: 'Gizmo Viewport',
    description: 'Viewport-style orientation gizmo.',
    path: '/core/controls/gizmoviewport',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'GizmoViewcube',
    category: 'Controls',
    title: 'Gizmo Viewcube',
    description: 'Viewcube-style orientation gizmo.',
    path: '/core/controls/gizmoviewcube',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Abstractions ==============================
  {
    name: 'AsciiRenderer',
    category: 'Abstractions',
    title: 'ASCII Renderer',
    description: 'Render the 3D scene as ASCII art characters.',
    path: '/core/abstractions/asciirenderer',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Billboard',
    category: 'Abstractions',
    title: 'Billboard',
    description: 'Objects that always face the camera.',
    path: '/core/abstractions/billboard',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Clone',
    category: 'Abstractions',
    title: 'Clone',
    description: 'Clone and reuse geometries and materials.',
    path: '/core/abstractions/clone',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Type issues',
    rendererSupport: 'universal',
  },
  {
    name: 'ComputedAttribute',
    category: 'Abstractions',
    title: 'Computed Attribute',
    description: 'Dynamically computed geometry attributes.',
    path: '/core/abstractions/computedattribute',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Unused @ts-expect-error',
    rendererSupport: 'universal',
  },
  {
    name: 'Example',
    category: 'Abstractions',
    title: 'Example',
    description: 'Example counter component demonstration.',
    path: '/core/abstractions/example',
    structure: 3,
    imports: 2,
    types: 2,
    tests: 1,
    notes: 'Cross-component imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Instances',
    category: 'Abstractions',
    title: 'Instances',
    description: 'Efficient instanced rendering for many objects.',
    path: '/core/abstractions/instances',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Type issues',
    rendererSupport: 'universal',
  },
  {
    name: 'Sampler',
    category: 'Abstractions',
    title: 'Sampler',
    description: 'Sample points on mesh surfaces.',
    path: '/core/abstractions/sampler',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenSpace',
    category: 'Abstractions',
    title: 'Screen Space',
    description: 'Render objects in screen space coordinates.',
    path: '/core/abstractions/screenspace',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Svg',
    category: 'Abstractions',
    title: 'SVG',
    description: 'Render SVG graphics in 3D space.',
    path: '/core/abstractions/svg',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Effects',
    category: 'Abstractions',
    title: 'Effects',
    description: 'Post-processing effects wrapper.',
    path: '/abstractions/effects',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Needs TSL shader conversion',
    rendererSupport: 'legacy-only',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },

  //* Effects ==============================
  {
    name: 'CameraShake',
    category: 'Effects',
    title: 'Camera Shake',
    description: 'Add camera shake effects for impact and motion.',
    path: '/core/effects/camerashake',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'Cloud',
    category: 'Effects',
    title: 'Cloud',
    description: 'Volumetric cloud effects.',
    path: '/core/effects/cloud',
    structure: 3,
    imports: 2,
    types: 2,
    tests: 1,
    notes: 'Cross-component imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Sparkles',
    category: 'Effects',
    title: 'Sparkles',
    description: 'Particle sparkle effects.',
    path: '/core/effects/sparkles',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 3,
    tslConversion: 3,
  },

  //* Geometry ==============================
  {
    name: 'CatmullRomLine',
    category: 'Geometry',
    title: 'Catmull-Rom Line',
    description: 'Smooth Catmull-Rom curve lines.',
    path: '/core/geometry/catmullromline',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CubicBezierLine',
    category: 'Geometry',
    title: 'Cubic Bezier Line',
    description: 'Cubic Bezier curve lines.',
    path: '/core/geometry/cubicbezierline',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CurveModifier',
    category: 'Geometry',
    title: 'Curve Modifier',
    description: 'Deform geometry along a curve path.',
    path: '/core/geometry/curvemodifier',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Decal',
    category: 'Geometry',
    title: 'Decal',
    description: 'Project decals onto mesh surfaces.',
    path: '/core/geometry/decal',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Detailed',
    category: 'Geometry',
    title: 'Detailed',
    description: 'Level of detail (LOD) system for optimization. (Zoom in to see the effect)',
    path: '/core/geometry/detailed',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Edges',
    category: 'Geometry',
    title: 'Edges',
    description: 'Render mesh edges with customizable appearance.',
    path: '/core/geometry/edges',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Might Check for imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Line',
    category: 'Geometry',
    title: 'Line',
    description: 'Render lines in 3D space.',
    path: '/core/geometry/line',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Points',
    category: 'Geometry',
    title: 'Points',
    description: 'Point cloud rendering.',
    path: '/core/geometry/points',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'QuadraticBezierLine',
    category: 'Geometry',
    title: 'Quadratic Bezier Line',
    description: 'Quadratic Bezier curve lines.',
    path: '/core/geometry/quadraticbezierline',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'RoundedBox',
    category: 'Geometry',
    title: 'Rounded Box',
    description: 'Box geometry with rounded edges.',
    path: '/core/geometry/roundedbox',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenQuad',
    category: 'Geometry',
    title: 'Screen Quad',
    description: 'Fullscreen quad for post-processing effects.',
    path: '/core/geometry/screenquad',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Segments',
    category: 'Geometry',
    title: 'Segments',
    description: 'Individual line segments with colors and styles.',
    path: '/core/geometry/segments',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Text3D',
    category: 'Geometry',
    title: 'Text3D',
    description: '3D text geometry with extrusion.',
    path: '/core/geometry/text3d',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Trail',
    category: 'Geometry',
    title: 'Trail',
    description: 'Motion trail effects for moving objects.',
    path: '/core/geometry/trail',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'switched from meshline, needs update for width',
    rendererSupport: 'universal',
  },
  {
    name: 'Wireframe',
    category: 'Geometry',
    title: 'Wireframe',
    description: 'Wireframe rendering for meshes.',
    path: '/core/geometry/wireframe',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Incorrectly in core',
    rendererSupport: 'legacy-only',
  },

  //* Helpers ==============================
  {
    name: 'CycleRaycast',
    category: 'Helpers',
    title: 'Cycle Raycast',
    description: 'Cycle through overlapping raycasted objects.',
    path: '/core/helpers/cycleraycast',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Fbo',
    category: 'Helpers',
    title: 'FBO / useFBO',
    description: 'Framebuffer object helper for render targets.',
    path: '/helpers/fbo',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'Html',
    category: 'Helpers',
    title: 'HTML',
    description: 'Overlay HTML content on 3D objects.',
    path: '/core/helpers/html',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PointMaterial',
    category: 'Helpers',
    title: 'Point Material',
    description: 'Material helper for point rendering.',
    path: '/core/helpers/pointmaterial',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'very small on webgpu, needs concept refactor',
    rendererSupport: 'universal',
  },
  {
    name: 'PositionalAudio',
    category: 'Helpers',
    title: 'Positional Audio',
    description: '3D positional audio in space.',
    path: '/core/helpers/positionalaudio',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'SpriteAnimator',
    category: 'Helpers',
    title: 'Sprite Animator',
    description: 'Animate sprite sheets.',
    path: '/core/helpers/spriteanimator',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'SOmething weird with framecount/setup',
    rendererSupport: 'universal',
  },
  {
    name: 'Text',
    category: 'Helpers',
    title: 'Text',
    description: '2D text rendering with Troika.',
    path: '/core/helpers/text',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useAnimations',
    category: 'Helpers',
    title: 'useAnimations',
    description: 'Hook for managing GLTF animations.',
    path: '/core/helpers/useanimations',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useContextBridge',
    category: 'Helpers',
    title: 'useContextBridge',
    description: 'Bridge React contexts across portals.',
    path: '/core/helpers/usecontextbridge',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useHelper',
    category: 'Helpers',
    title: 'useHelper',
    description: 'Attach Three.js helpers to objects.',
    path: '/core/helpers/usehelper',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Loaders ==============================
  {
    name: 'CubeTexture',
    category: 'Loaders',
    title: 'Cube Texture',
    description: 'Load cube map textures for environments.',
    path: '/core/loaders/cubetexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Loader',
    category: 'Loaders',
    title: 'Loader',
    description: 'Loading UI component.',
    path: '/core/loaders/loader',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'MatcapTexture',
    category: 'Loaders',
    title: 'Matcap Texture',
    description: 'Load matcap textures for materials.',
    path: '/core/loaders/matcaptexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Preload',
    category: 'Loaders',
    title: 'Preload',
    description: 'Preload all scene assets.',
    path: '/core/loaders/preload',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenVideoTexture',
    category: 'Loaders',
    title: 'Screen Video Texture',
    description: 'Capture screen as video texture.',
    path: '/core/loaders/screenvideotexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'TrailTexture',
    category: 'Loaders',
    title: 'Trail Texture',
    description: 'Dynamic trail texture generation.',
    path: '/core/loaders/trailtexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useFBX',
    category: 'Loaders',
    title: 'useFBX',
    description: 'Load FBX model files.',
    path: '/core/loaders/usefbx',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useFont',
    category: 'Loaders',
    title: 'useFont',
    description: 'Load Three.js font files for Text3D.',
    path: '/core/loaders/usefont',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useGLTF',
    category: 'Loaders',
    title: 'useGLTF',
    description: 'Load GLTF/GLB model files.',
    path: '/core/loaders/usegltf',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useKTX2',
    category: 'Loaders',
    title: 'useKTX2',
    description: 'Load compressed KTX2 textures.',
    path: '/core/loaders/usektx2',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useProgress',
    category: 'Loaders',
    title: 'useProgress',
    description: 'Track asset loading progress.',
    path: '/core/loaders/useprogress',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useSpriteLoader',
    category: 'Loaders',
    title: 'useSpriteLoader',
    description: 'Load sprite textures.',
    path: '/core/loaders/usespriteloader',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useTexture',
    category: 'Loaders',
    title: 'useTexture',
    description: 'Load image textures.',
    path: '/core/loaders/usetexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'VideoTexture',
    category: 'Loaders',
    title: 'Video Texture',
    description: 'Use video as texture.',
    path: '/core/loaders/videotexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'WebcamVideoTexture',
    category: 'Loaders',
    title: 'Webcam Video Texture',
    description: 'Use webcam feed as texture.',
    path: '/core/loaders/webcamvideotexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Performance ==============================
  {
    name: 'AdaptiveDpr',
    category: 'Performance',
    title: 'Adaptive DPR',
    description: 'Automatically adjust pixel ratio based on performance.',
    path: '/core/performance/adaptivedpr',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'AdaptiveEvents',
    category: 'Performance',
    title: 'Adaptive Events',
    description: 'Throttle event handling based on performance.',
    path: '/core/performance/adaptiveevents',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'DetectGPU',
    category: 'Performance',
    title: 'Detect GPU',
    description: 'Detect GPU tier and capabilities.',
    path: '/core/performance/detectgpu',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'meshBounds',
    category: 'Performance',
    title: 'Mesh Bounds',
    description: 'Faster raycasting using bounding boxes.',
    path: '/core/performance/meshbounds',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PerformanceMonitor',
    category: 'Performance',
    title: 'Performance Monitor',
    description: 'Monitor and react to performance changes.',
    path: '/core/performance/performancemonitor',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Stats',
    category: 'Performance',
    title: 'Stats',
    description: 'Display FPS and performance stats.',
    path: '/core/performance/stats',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'StatsGl',
    category: 'Performance',
    title: 'Stats GL',
    description: 'WebGL-specific performance stats.',
    path: '/core/performance/statsgl',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Portal ==============================
  {
    name: 'Fisheye',
    category: 'Portal',
    title: 'Fisheye',
    description: 'Fisheye camera effect.',
    path: '/core/portal/fisheye',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Hud',
    category: 'Portal',
    title: 'HUD',
    description: 'Heads-up display overlay.',
    path: '/portal/hud',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'Mask',
    category: 'Portal',
    title: 'Mask',
    description: 'Stencil masking for selective rendering.',
    path: '/core/portal/mask',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'RenderCubeTexture',
    category: 'Portal',
    title: 'Render Cube Texture',
    description: 'Render scene to cube texture.',
    path: '/portal/rendercubetexture',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'RenderTexture',
    category: 'Portal',
    title: 'Render Texture',
    description: 'Render scene to texture.',
    path: '/core/portal/rendertexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'View',
    category: 'Portal',
    title: 'View',
    description: 'Multiple viewport rendering.',
    path: '/core/portal/view',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Staging ==============================
  {
    name: 'Backdrop',
    category: 'Staging',
    title: 'Backdrop',
    description: 'Curved backdrop plane for staging.',
    path: '/core/staging/backdrop',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'BBAnchor',
    category: 'Staging',
    title: 'BB Anchor',
    description: 'Position elements relative to bounding box.',
    path: '/core/staging/bbanchor',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Bounds',
    category: 'Staging',
    title: 'Bounds',
    description: 'Fit camera to object bounds.',
    path: '/core/staging/bounds',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Center',
    category: 'Staging',
    title: 'Center',
    description: 'Center geometry at origin.',
    path: '/core/staging/center',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Environment',
    category: 'Staging',
    title: 'Environment',
    description: 'Environment maps and lighting.',
    path: '/core/staging/environment',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Float',
    category: 'Staging',
    title: 'Float',
    description: 'Floating animation effect.',
    path: '/core/staging/float',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Grid',
    category: 'Staging',
    title: 'Grid',
    description: 'Infinite grid helper.',
    path: '/core/staging/grid',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 3,
    tslConversion: 3,
  },
  {
    name: 'Lightformer',
    category: 'Staging',
    title: 'Lightformer',
    description: 'Shaped area lights for staging.',
    path: '/core/staging/lightformer',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Resize',
    category: 'Staging',
    title: 'Resize',
    description: 'Responsive resizing container.',
    path: '/core/staging/resize',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenSizer',
    category: 'Staging',
    title: 'Screen Sizer',
    description: 'Scale based on screen size.',
    path: '/core/staging/screensizer',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Shadow',
    category: 'Staging',
    title: 'Shadow',
    description: 'Contact shadow effects.',
    path: '/core/staging/shadow',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Sky',
    category: 'Staging',
    title: 'Sky',
    description: 'Procedural sky shader.',
    path: '/core/staging/sky',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'SpotLight',
    category: 'Staging',
    title: 'SpotLight',
    description: 'Enhanced spotlight with volumetric effects.',
    path: '/core/staging/spotlight',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Stage',
    category: 'Staging',
    title: 'Stage',
    description: 'Auto-staging with lights and shadows.',
    path: '/core/staging/stage',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Stars',
    category: 'Staging',
    title: 'Stars',
    description: 'Procedural starfield.',
    path: '/core/staging/stars',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 3,
    tslConversion: 3,
  },
  {
    name: 'useBoxProjectedEnv',
    category: 'Staging',
    title: 'useBoxProjectedEnv',
    description: 'Box-projected environment maps.',
    path: '/core/staging/useboxprojectedenv',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'legacy-only',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'useEnvironment',
    category: 'Staging',
    title: 'useEnvironment',
    description: 'Hook for loading environment maps.',
    path: '/core/staging/useenvironment',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* UI ==============================
  {
    name: 'useAspect',
    category: 'UI',
    title: 'useAspect',
    description: 'Maintain aspect ratio scaling.',
    path: '/core/ui/useaspect',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useCursor',
    category: 'UI',
    title: 'useCursor',
    description: 'Change cursor on hover interactions.',
    path: '/core/ui/usecursor',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useIntersect',
    category: 'UI',
    title: 'useIntersect',
    description: 'Detect when objects intersect viewport.',
    path: '/core/ui/useintersect',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Materials (Dual renderer - need both legacy and WebGPU) ==============================
  {
    name: 'AccumulativeShadows',
    category: 'Materials',
    title: 'Accumulative Shadows',
    description: 'Soft accumulative shadow ground.',
    path: '/materials/accumulativeshadows',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority for WebGPU',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'BakeShadows',
    category: 'Materials',
    title: 'Bake Shadows',
    description: 'Bake shadows to texture.',
    path: '/materials/bakeshadows',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'BlurPass',
    category: 'Materials',
    title: 'Blur Pass',
    description: 'Gaussian blur post-processing.',
    path: '/materials/blurpass',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'Caustics',
    category: 'Materials',
    title: 'Caustics',
    description: 'Light caustics effect.',
    path: '/materials/caustics',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority for WebGPU',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'ContactShadows',
    category: 'Materials',
    title: 'Contact Shadows',
    description: 'Soft contact shadows.',
    path: '/core/staging/contactshadows',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'TSL partial: opacity/blur work, color prop needs rewrite (uses multiply blend workaround)',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 2,
    tslConversion: 2,
  },
  {
    name: 'ConvolutionMaterial',
    category: 'Materials',
    title: 'Convolution Material',
    description: 'Convolution blur material.',
    path: '/materials/convolutionmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'DiscardMaterial',
    category: 'Materials',
    title: 'Discard Material',
    description: 'Material that discards all fragments.',
    path: '/materials/discardmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'GradientTexture',
    category: 'Materials',
    title: 'Gradient Texture',
    description: 'Procedural gradient texture.',
    path: '/materials/gradienttexture',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'Image',
    category: 'Materials',
    title: 'Image',
    description: 'Image plane with shader effects.',
    path: '/materials/image',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshDiscardMaterial',
    category: 'Materials',
    title: 'Mesh Discard Material',
    description: 'Material that discards mesh fragments.',
    path: '/materials/meshdiscardmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshDistortMaterial',
    category: 'Materials',
    title: 'Mesh Distort Material',
    description: 'Noise-based vertex distortion.',
    path: '/materials/meshdistortmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshPortalMaterial',
    category: 'Materials',
    title: 'Mesh Portal Material',
    description: 'Portal effect through mesh.',
    path: '/materials/meshportalmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshReflectorMaterial',
    category: 'Materials',
    title: 'Mesh Reflector Material',
    description: 'Planar reflections.',
    path: '/materials/meshreflectormaterial',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshRefractionMaterial',
    category: 'Materials',
    title: 'Mesh Refraction Material',
    description: 'Refraction through glass-like materials.',
    path: '/materials/meshrefractionmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshTransmissionMaterial',
    category: 'Materials',
    title: 'Mesh Transmission Material',
    description: 'Glass-like transmission material.',
    path: '/materials/meshtransmissionmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'MeshWobbleMaterial',
    category: 'Materials',
    title: 'Mesh Wobble Material',
    description: 'Wobbly animated material.',
    path: '/materials/meshwobblematerial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'Outlines',
    category: 'Materials',
    title: 'Outlines',
    description: 'Mesh outline effect.',
    path: '/materials/outlines',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'shaderMaterial',
    category: 'Materials',
    title: 'Shader Material',
    description: 'Custom shader material factory.',
    path: '/materials/shadermaterial',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'High priority - core utility',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'SoftShadows',
    category: 'Materials',
    title: 'Soft Shadows',
    description: 'Percentage closer soft shadows.',
    path: '/materials/softshadows',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'SpotLightMaterial',
    category: 'Materials',
    title: 'SpotLight Material',
    description: 'Volumetric spotlight material.',
    path: '/materials/spotlightmaterial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },
  {
    name: 'WireframeMaterial',
    category: 'Materials',
    title: 'Wireframe Material',
    description: 'Stylized wireframe material.',
    path: '/materials/wireframematerial',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: 3,
    webgpuStatus: 1,
    tslConversion: 1,
  },

  //* External ==============================
  {
    name: 'Bvh',
    category: 'External',
    title: 'BVH',
    description: 'Bounding Volume Hierarchy for fast raycasting.',
    path: '/external/bvh',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CameraControls',
    category: 'External',
    title: 'Camera Controls',
    description: 'Advanced camera controls library.',
    path: '/external/cameracontrols',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Facemesh',
    category: 'External',
    title: 'Facemesh',
    description: 'MediaPipe face mesh integration.',
    path: '/external/facemesh',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'FaceLandmarker',
    category: 'External',
    title: 'Face Landmarker',
    description: 'MediaPipe face landmark detection.',
    path: '/external/facelandmarker',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'NormalTexture',
    category: 'External',
    title: 'Normal Texture',
    description: 'Generate normal maps from images.',
    path: '/external/normaltexture',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Splat',
    category: 'External',
    title: 'Splat',
    description: 'Gaussian splatting renderer.',
    path: '/external/splat',
    structure: 3,
    imports: 3,
    types: 3,
    tests: 1,
    notes: '',
    rendererSupport: 'universal',
  },

  //* Experimental ==============================
  {
    name: 'MarchingCubes',
    category: 'Experimental',
    title: 'Marching Cubes',
    description: 'Marching cubes isosurface extraction.',
    path: '/experimental/marchingcubes',
    structure: 3,
    imports: 3,
    types: 2,
    tests: 1,
    notes: 'Utils import, type issues',
    rendererSupport: 'universal',
  },
]

//* Helper Functions ==============================

// Get all components that have working demos
export const getDemos = () => components.filter((c) => c.component !== undefined)

// Get component by name (for ExampleCard, etc.)
export const getComponent = (name: string) => {
  const component = components.find((c) => c.name === name)
  if (!component) throw new Error(`Component ${name} not found`)
  return component
}

// Alias for backward compatibility
export const getMetadata = getComponent

// Check if a component has a demo
export const hasDemo = (name: string) => {
  const component = components.find((c) => c.name === name)
  return component?.component !== undefined
}

// Get components by category
export const getByCategory = (category: Category) => components.filter((c) => c.category === category)

// Get components by renderer support type
export const getByRendererSupport = (support: RendererSupport) =>
  components.filter((c) => c.rendererSupport === support)

// Get components needing WebGPU work
export const getWebGPUTodo = () =>
  components.filter(
    (c) => (c.rendererSupport === 'dual' || c.rendererSupport === 'legacy-only') && c.webgpuStatus !== 3
  )

// Derive tier from category for backward compatibility with sidebar
export const getTier = (c: DreiComponent): Tier => {
  if (c.category === 'External') return 'external'
  if (c.category === 'Experimental') return 'experimental'
  return 'core'
}

// Backward compatibility: Demo type alias
export type Demo = DreiComponent & { component: React.ComponentType }

// Backward compatibility: demos array (only components with demos)
export const demos = getDemos() as Demo[]
