//* Component Registry ==============================
// Single source of truth for all drei components, their demos, and status tracking.
// Each conceptual component has ONE entry, with renderer support tracked via columns.

//* Demo Imports ==============================

// Core - Cameras
import OrthographicCameraDemo from './core/cameras/OrthographicCamera'
import PerspectiveCameraDemo from './core/cameras/PerspectiveCamera'
import UseCustomRaycastDemo from './core/cameras/UseCustomRaycast'

// Core - Controls
import ArcballControlsDemo from './core/controls/ArcballControls'
import OrbitControlsDemo from './core/controls/OrbitControls'
import MapControlsDemo from './core/controls/MapControls'
import TrackballControlsDemo from './core/controls/TrackballControls'
import FlyControlsDemo from './core/controls/FlyControls'
import PointerLockControlsDemo from './core/controls/PointLockControls'
import DeviceOrientationControlsDemo from './core/controls/DeviceOrientationControls'
import DragControlsDemo from './core/controls/DragControls'
import FirstPersonControlsDemo from './core/controls/FirstPersonControls'
import KeyboardControlsDemo from './core/controls/KeyboardControls'
import PivotControlsDemo from './core/controls/PivotControls'
import TransformControlsDemo from './core/controls/TransformControls'
import MotionPathControlsDemo from './core/controls/MotionPathControls'
import PresentationControlsDemo from './core/controls/PresentationControls'
import FaceControlsDemo from './core/controls/FaceControls'
import SelectDemo from './core/controls/Select'
import ScrollControlsDemo from './core/controls/ScrollControls'
import GizmoHelperDemo from './core/controls/GizmoHelper'

// Core - Abstractions
import AsciiRendererDemo from './core/abstractions/AsciiRenderer'
import BillboardDemo from './core/abstractions/Billboard'
import CloneDemo from './core/abstractions/Clone'
import ComputedAttributeDemo from './core/abstractions/ComputedAttribute'
import ExampleDemo from './core/abstractions/Example'
import InstancesDemo from './core/abstractions/Instances'
import SamplerDemo from './core/abstractions/Sampler'
import ScreenSpaceDemo from './core/abstractions/ScreenSpace'
import SvgDemo from './core/abstractions/Svg'

// Core - Effects
import CameraShakeDemo from './core/effects/CameraShake'
import CloudDemo from './core/effects/Cloud'
import SparklesDemo from './core/effects/Sparkles'

// Core - Geometry
import CatmullRomLineDemo from './core/geometry/CatmullRomLine'
import CubicBezierLineDemo from './core/geometry/CubicBezierLine'
import CurveModifierDemo from './core/geometry/CurveModifier'
import DecalDemo from './core/geometry/Decal'
import DetailedDemo from './core/geometry/Detailed'
import EdgesDemo from './core/geometry/Edges'
import LineDemo from './core/geometry/Line'
import PointsDemo from './core/geometry/Points'
import QuadraticBezierLineDemo from './core/geometry/QuadraticBezierLine'
import RoundedBoxDemo from './core/geometry/RoundedBox'
import ScreenQuadDemo from './core/geometry/ScreenQuad'
import SegmentsDemo from './core/geometry/Segments'
import Text3DDemo from './core/geometry/Text3D'
import TrailDemo from './core/geometry/Trail'
import WireframeDemo from './core/geometry/Wireframe'

// Core - Helpers
import CycleRaycastDemo from './core/helpers/CycleRaycast'
import FboDemo from './core/helpers/Fbo'
import HtmlDemo from './core/helpers/Html'
import PointMaterialDemo from './core/helpers/PointMaterial'
import PositionalAudioDemo from './core/helpers/PositionalAudio'
import SpriteAnimatorDemo from './core/helpers/SpriteAnimator'
import TextDemo from './external/Text'
import UseAnimationsDemo from './core/helpers/useAnimations'
import UseContextBridgeDemo from './core/helpers/useContextBridge'

// Core - Loaders
import CubeTextureDemo from './core/loaders/CubeTexture'
import LoaderDemo from './core/loaders/Loader'
import MatcapTextureDemo from './core/loaders/MatcapTexture'
import PreloadDemo from './core/loaders/Preload'
import ScreenVideoTextureDemo from './core/loaders/ScreenVideoTexture'
import TrailTextureDemo from './core/loaders/TrailTexture'
import UseFBXDemo from './core/loaders/useFBX'
import UseFontDemo from './core/loaders/useFont'
import UseGLTFDemo from './core/loaders/useGLTF'
import UseKTX2Demo from './core/loaders/useKTX2'
import UseProgressDemo from './core/loaders/useProgress'
import UseSpriteLoaderDemo from './core/loaders/useSpriteLoader'
import UseTextureDemo from './core/loaders/useTexture'
import VideoTextureDemo from './core/loaders/VideoTexture'
import WebcamVideoTextureDemo from './core/loaders/WebcamVideoTexture'

// Core - Performance
import AdaptiveDprDemo from './core/performance/AdaptiveDpr'
import AdaptiveEventsDemo from './core/performance/AdaptiveEvents'
import DetectGPUDemo from './core/performance/DetectGPU'
import MeshBoundsDemo from './core/performance/meshBounds'
import PerformanceMonitorDemo from './core/performance/PerformanceMonitor'
import StatsDemo from './core/performance/Stats'
import StatsGlDemo from './core/performance/StatsGl'

// Core - Portal
import FisheyeDemo from './core/portal/Fisheye'
import MaskDemo from './core/portal/Mask'
import RenderTextureDemo from './core/portal/RenderTexture'
import ViewDemo from './core/portal/View'

// Core - Staging
import BackdropDemo from './core/staging/Backdrop'
import BBAnchorDemo from './core/staging/BBAnchor'
import BoundsDemo from './core/staging/Bounds'
import CenterDemo from './core/staging/Center'
import EnvironmentDemo from './core/staging/Environment'
import FloatDemo from './core/staging/Float'
import GridDemo from './core/staging/Grid'
import LightformerDemo from './core/staging/Lightformer'
import ResizeDemo from './core/staging/Resize'
import ScreenSizerDemo from './core/staging/ScreenSizer'
import ShadowDemo from './core/staging/Shadow'
import SkyDemo from './core/staging/Sky'
import StageDemo from './core/staging/Stage'
import StarsDemo from './core/staging/Stars'
import UseBoxProjectedEnvDemo from './core/staging/useBoxProjectedEnv'
import UseEnvironmentDemo from './core/staging/useEnvironment'

// Core - UI
import UseAspectDemo from './core/ui/useAspect'
import UseCursorDemo from './core/ui/useCursor'
import UseIntersectDemo from './core/ui/useIntersect'

//* Types ==============================

export type Status = '🟢' | '🟡' | '🔴' | '⚪'

// Renderer support indicates which renderer implementations exist
// - 'universal': Works with any renderer, no shader code needed
// - 'legacy-only': Only WebGL/legacy implementation exists
// - 'webgpu-only': Only WebGPU/TSL implementation exists (rare)
// - 'dual': Has both legacy and WebGPU implementations
export type RendererSupport = 'universal' | 'legacy-only' | 'webgpu-only' | 'dual'

// Categories for grouping - simplified from previous tier system
export type Category =
  | 'Cameras'
  | 'Controls'
  | 'Abstractions'
  | 'Effects'
  | 'Geometry'
  | 'Helpers'
  | 'Loaders'
  | 'Performance'
  | 'Portal'
  | 'Staging'
  | 'UI'
  | 'Materials'
  | 'External'
  | 'Experimental'

export interface DreiComponent {
  // Identity
  name: string
  category: Category
  title: string
  description: string

  // Demo routing - path is always present, component only if demo exists
  path: string
  component?: React.ComponentType

  // Base status tracking (applies to core/universal implementations)
  structure: Status
  imports: Status
  types: Status
  tests: Status
  notes: string

  // Renderer support - determines which columns appear in dashboard
  rendererSupport: RendererSupport

  // Legacy (WebGL) specific status - only for legacy-only or dual
  legacyStatus?: Status

  // WebGPU specific status - only for webgpu-only or dual
  webgpuStatus?: Status
  tslConversion?: Status // TSL shader conversion progress
}

// Legacy Tier type for backward compatibility with sidebar grouping
export type Tier = 'core' | 'external' | 'experimental'

//* Component Registry ==============================
// One entry per conceptual component. Renderer-specific status tracked in columns.

export const components: DreiComponent[] = [
  //* Cameras ==============================
  {
    name: 'OrthographicCamera',
    category: 'Cameras',
    title: 'Orthographic Camera',
    description: 'A camera that uses an orthographic projection.',
    path: '/core/cameras/orthographic',
    component: OrthographicCameraDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Example created',
    rendererSupport: 'universal',
  },
  {
    name: 'PerspectiveCamera',
    category: 'Cameras',
    title: 'Perspective Camera',
    description: 'A camera that uses a perspective projection.',
    path: '/core/cameras/perspective',
    component: PerspectiveCameraDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Example created',
    rendererSupport: 'universal',
  },
  {
    name: 'useCustomRaycast',
    category: 'Cameras',
    title: 'Use Custom Raycast',
    description: 'Hook for custom raycast behavior.',
    path: '/core/cameras/usecustomraycast',
    component: UseCustomRaycastDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CubeCamera',
    category: 'Cameras',
    title: 'Cube Camera',
    description: 'Camera for rendering cube maps / environment captures.',
    path: '/cameras/cubecamera',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },

  //* Controls ==============================
  {
    name: 'OrbitControls',
    category: 'Controls',
    title: 'Orbit Controls',
    description: 'A control that allows the camera to orbit around the scene.',
    path: '/core/controls/orbit',
    component: OrbitControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Example created',
    rendererSupport: 'universal',
  },
  {
    name: 'ArcballControls',
    category: 'Controls',
    title: 'Arcball Controls',
    description: 'A control that allows the camera to orbit around the scene.',
    path: '/core/controls/arcball',
    component: ArcballControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'MapControls',
    category: 'Controls',
    title: 'Map Controls',
    description: 'A control that allows the camera to move around the scene.',
    path: '/core/controls/map',
    component: MapControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'PointerLockControls',
    category: 'Controls',
    title: 'Pointer Lock Controls',
    description: 'A control that allows the camera to lock to the scene.',
    path: '/core/controls/pointerlock',
    component: PointerLockControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'TrackballControls',
    category: 'Controls',
    title: 'Trackball Controls',
    description: 'A control that allows the camera to orbit around the scene.',
    path: '/core/controls/trackball',
    component: TrackballControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'FlyControls',
    category: 'Controls',
    title: 'Fly Controls',
    description: 'A control that allows the camera to fly around the scene.',
    path: '/core/controls/fly',
    component: FlyControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'DeviceOrientationControls',
    category: 'Controls',
    title: 'Device Orientation Controls',
    description: 'Control camera with device orientation (mobile/gyroscope).',
    path: '/core/controls/deviceorientation',
    component: DeviceOrientationControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'DragControls',
    category: 'Controls',
    title: 'Drag Controls',
    description: 'Drag objects in the scene with mouse.',
    path: '/core/controls/drag',
    component: DragControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'FirstPersonControls',
    category: 'Controls',
    title: 'First Person Controls',
    description: 'First-person shooter style camera controls.',
    path: '/core/controls/firstperson',
    component: FirstPersonControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'KeyboardControls',
    category: 'Controls',
    title: 'Keyboard Controls',
    description: 'Keyboard input management for scene interactions.',
    path: '/core/controls/keyboard',
    component: KeyboardControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PivotControls',
    category: 'Controls',
    title: 'Pivot Controls',
    description: 'Transform gizmo for moving, rotating, and scaling objects.',
    path: '/core/controls/pivot',
    component: PivotControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Multi-file component',
    rendererSupport: 'universal',
  },
  {
    name: 'TransformControls',
    category: 'Controls',
    title: 'Transform Controls',
    description: 'Three.js TransformControls for precise object manipulation.',
    path: '/core/controls/transform',
    component: TransformControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'MotionPathControls',
    category: 'Controls',
    title: 'Motion Path Controls',
    description: 'Animate camera along a curved path.',
    path: '/core/controls/motionpath',
    component: MotionPathControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PresentationControls',
    category: 'Controls',
    title: 'Presentation Controls',
    description: 'Drag-to-rotate controls ideal for product showcases.',
    path: '/core/controls/presentation',
    component: PresentationControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'FaceControls',
    category: 'Controls',
    title: 'Face Controls',
    description: 'Control camera with face tracking (requires webcam and MediaPipe).',
    path: '/core/controls/face',
    component: FaceControlsDemo,
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    tests: '🔴',
    notes: 'Cross-tier imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Select',
    category: 'Controls',
    title: 'Select',
    description: 'Click and box-select objects in the scene.',
    path: '/core/controls/select',
    component: SelectDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScrollControls',
    category: 'Controls',
    title: 'Scroll Controls',
    description: 'Create scroll-based animations and interactions.',
    path: '/core/controls/scroll',
    component: ScrollControlsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'GizmoHelper',
    category: 'Controls',
    title: 'Gizmo Helper',
    description: 'Visual orientation helper showing scene axes.',
    path: '/core/controls/gizmo',
    component: GizmoHelperDemo,
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    tests: '🔴',
    notes: 'Case sensitivity, cross-tier',
    rendererSupport: 'universal',
  },
  {
    name: 'GizmoViewport',
    category: 'Controls',
    title: 'Gizmo Viewport',
    description: 'Viewport-style orientation gizmo.',
    path: '/core/controls/gizmoviewport',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'GizmoViewcube',
    category: 'Controls',
    title: 'Gizmo Viewcube',
    description: 'Viewcube-style orientation gizmo.',
    path: '/core/controls/gizmoviewcube',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Abstractions ==============================
  {
    name: 'AsciiRenderer',
    category: 'Abstractions',
    title: 'ASCII Renderer',
    description: 'Render the 3D scene as ASCII art characters.',
    path: '/core/abstractions/asciirenderer',
    component: AsciiRendererDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Billboard',
    category: 'Abstractions',
    title: 'Billboard',
    description: 'Objects that always face the camera.',
    path: '/core/abstractions/billboard',
    component: BillboardDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Clone',
    category: 'Abstractions',
    title: 'Clone',
    description: 'Clone and reuse geometries and materials.',
    path: '/core/abstractions/clone',
    component: CloneDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Type issues',
    rendererSupport: 'universal',
  },
  {
    name: 'ComputedAttribute',
    category: 'Abstractions',
    title: 'Computed Attribute',
    description: 'Dynamically computed geometry attributes.',
    path: '/core/abstractions/computedattribute',
    component: ComputedAttributeDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Unused @ts-expect-error',
    rendererSupport: 'universal',
  },
  {
    name: 'Example',
    category: 'Abstractions',
    title: 'Example',
    description: 'Example counter component demonstration.',
    path: '/core/abstractions/example',
    component: ExampleDemo,
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    tests: '🔴',
    notes: 'Cross-component imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Instances',
    category: 'Abstractions',
    title: 'Instances',
    description: 'Efficient instanced rendering for many objects.',
    path: '/core/abstractions/instances',
    component: InstancesDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Type issues',
    rendererSupport: 'universal',
  },
  {
    name: 'Sampler',
    category: 'Abstractions',
    title: 'Sampler',
    description: 'Sample points on mesh surfaces.',
    path: '/core/abstractions/sampler',
    component: SamplerDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenSpace',
    category: 'Abstractions',
    title: 'Screen Space',
    description: 'Render objects in screen space coordinates.',
    path: '/core/abstractions/screenspace',
    component: ScreenSpaceDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Svg',
    category: 'Abstractions',
    title: 'SVG',
    description: 'Render SVG graphics in 3D space.',
    path: '/core/abstractions/svg',
    component: SvgDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Effects',
    category: 'Abstractions',
    title: 'Effects',
    description: 'Post-processing effects wrapper.',
    path: '/abstractions/effects',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Needs TSL shader conversion',
    rendererSupport: 'legacy-only',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },

  //* Effects ==============================
  {
    name: 'CameraShake',
    category: 'Effects',
    title: 'Camera Shake',
    description: 'Add camera shake effects for impact and motion.',
    path: '/core/effects/camerashake',
    component: CameraShakeDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import issue',
    rendererSupport: 'universal',
  },
  {
    name: 'Cloud',
    category: 'Effects',
    title: 'Cloud',
    description: 'Volumetric cloud effects.',
    path: '/core/effects/cloud',
    component: CloudDemo,
    structure: '🟢',
    imports: '🟡',
    types: '🟡',
    tests: '🔴',
    notes: 'Cross-component imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Sparkles',
    category: 'Effects',
    title: 'Sparkles',
    description: 'Particle sparkle effects.',
    path: '/core/effects/sparkles',
    component: SparklesDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Geometry ==============================
  {
    name: 'CatmullRomLine',
    category: 'Geometry',
    title: 'Catmull-Rom Line',
    description: 'Smooth Catmull-Rom curve lines.',
    path: '/core/geometry/catmullromline',
    component: CatmullRomLineDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CubicBezierLine',
    category: 'Geometry',
    title: 'Cubic Bezier Line',
    description: 'Cubic Bezier curve lines.',
    path: '/core/geometry/cubicbezierline',
    component: CubicBezierLineDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CurveModifier',
    category: 'Geometry',
    title: 'Curve Modifier',
    description: 'Deform geometry along a curve path.',
    path: '/core/geometry/curvemodifier',
    component: CurveModifierDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Decal',
    category: 'Geometry',
    title: 'Decal',
    description: 'Project decals onto mesh surfaces.',
    path: '/core/geometry/decal',
    component: DecalDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Detailed',
    category: 'Geometry',
    title: 'Detailed',
    description: 'Level of detail (LOD) system for optimization. (Zoom in to see the effect)',
    path: '/core/geometry/detailed',
    component: DetailedDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Edges',
    category: 'Geometry',
    title: 'Edges',
    description: 'Render mesh edges with customizable appearance.',
    path: '/core/geometry/edges',
    component: EdgesDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Might Check for imports',
    rendererSupport: 'universal',
  },
  {
    name: 'Line',
    category: 'Geometry',
    title: 'Line',
    description: 'Render lines in 3D space.',
    path: '/core/geometry/line',
    component: LineDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Points',
    category: 'Geometry',
    title: 'Points',
    description: 'Point cloud rendering.',
    path: '/core/geometry/points',
    component: PointsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'QuadraticBezierLine',
    category: 'Geometry',
    title: 'Quadratic Bezier Line',
    description: 'Quadratic Bezier curve lines.',
    path: '/core/geometry/quadraticbezierline',
    component: QuadraticBezierLineDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'RoundedBox',
    category: 'Geometry',
    title: 'Rounded Box',
    description: 'Box geometry with rounded edges.',
    path: '/core/geometry/roundedbox',
    component: RoundedBoxDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenQuad',
    category: 'Geometry',
    title: 'Screen Quad',
    description: 'Fullscreen quad for post-processing effects.',
    path: '/core/geometry/screenquad',
    component: ScreenQuadDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Segments',
    category: 'Geometry',
    title: 'Segments',
    description: 'Individual line segments with colors and styles.',
    path: '/core/geometry/segments',
    component: SegmentsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Text3D',
    category: 'Geometry',
    title: 'Text3D',
    description: '3D text geometry with extrusion.',
    path: '/core/geometry/text3d',
    component: Text3DDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Trail',
    category: 'Geometry',
    title: 'Trail',
    description: 'Motion trail effects for moving objects.',
    path: '/core/geometry/trail',
    component: TrailDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'switched from meshline, needs update for width',
    rendererSupport: 'universal',
  },
  {
    name: 'Wireframe',
    category: 'Geometry',
    title: 'Wireframe',
    description: 'Wireframe rendering for meshes.',
    path: '/core/geometry/wireframe',
    component: WireframeDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Incorrectly in core',
    rendererSupport: 'legacy-only',
  },

  //* Helpers ==============================
  {
    name: 'CycleRaycast',
    category: 'Helpers',
    title: 'Cycle Raycast',
    description: 'Cycle through overlapping raycasted objects.',
    path: '/core/helpers/cycleraycast',
    component: CycleRaycastDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Fbo',
    category: 'Helpers',
    title: 'FBO / useFBO',
    description: 'Framebuffer object helper for render targets.',
    path: '/helpers/fbo',
    component: FboDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'Html',
    category: 'Helpers',
    title: 'HTML',
    description: 'Overlay HTML content on 3D objects.',
    path: '/core/helpers/html',
    component: HtmlDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PointMaterial',
    category: 'Helpers',
    title: 'Point Material',
    description: 'Material helper for point rendering.',
    path: '/core/helpers/pointmaterial',
    component: PointMaterialDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'very small on webgpu, needs concept refactor',
    rendererSupport: 'universal',
  },
  {
    name: 'PositionalAudio',
    category: 'Helpers',
    title: 'Positional Audio',
    description: '3D positional audio in space.',
    path: '/core/helpers/positionalaudio',
    component: PositionalAudioDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'SpriteAnimator',
    category: 'Helpers',
    title: 'Sprite Animator',
    description: 'Animate sprite sheets.',
    path: '/core/helpers/spriteanimator',
    component: SpriteAnimatorDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'SOmething weird with framecount/setup',
    rendererSupport: 'universal',
  },
  {
    name: 'Text',
    category: 'Helpers',
    title: 'Text',
    description: '2D text rendering with Troika.',
    path: '/core/helpers/text',
    component: TextDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useAnimations',
    category: 'Helpers',
    title: 'useAnimations',
    description: 'Hook for managing GLTF animations.',
    path: '/core/helpers/useanimations',
    component: UseAnimationsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useContextBridge',
    category: 'Helpers',
    title: 'useContextBridge',
    description: 'Bridge React contexts across portals.',
    path: '/core/helpers/usecontextbridge',
    component: UseContextBridgeDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useHelper',
    category: 'Helpers',
    title: 'useHelper',
    description: 'Attach Three.js helpers to objects.',
    path: '/core/helpers/usehelper',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Loaders ==============================
  {
    name: 'CubeTexture',
    category: 'Loaders',
    title: 'Cube Texture',
    description: 'Load cube map textures for environments.',
    path: '/core/loaders/cubetexture',
    component: CubeTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Loader',
    category: 'Loaders',
    title: 'Loader',
    description: 'Loading UI component.',
    path: '/core/loaders/loader',
    component: LoaderDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'MatcapTexture',
    category: 'Loaders',
    title: 'Matcap Texture',
    description: 'Load matcap textures for materials.',
    path: '/core/loaders/matcaptexture',
    component: MatcapTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Preload',
    category: 'Loaders',
    title: 'Preload',
    description: 'Preload all scene assets.',
    path: '/core/loaders/preload',
    component: PreloadDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenVideoTexture',
    category: 'Loaders',
    title: 'Screen Video Texture',
    description: 'Capture screen as video texture.',
    path: '/core/loaders/screenvideotexture',
    component: ScreenVideoTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'TrailTexture',
    category: 'Loaders',
    title: 'Trail Texture',
    description: 'Dynamic trail texture generation.',
    path: '/core/loaders/trailtexture',
    component: TrailTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useFBX',
    category: 'Loaders',
    title: 'useFBX',
    description: 'Load FBX model files.',
    path: '/core/loaders/usefbx',
    component: UseFBXDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useFont',
    category: 'Loaders',
    title: 'useFont',
    description: 'Load Three.js font files for Text3D.',
    path: '/core/loaders/usefont',
    component: UseFontDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useGLTF',
    category: 'Loaders',
    title: 'useGLTF',
    description: 'Load GLTF/GLB model files.',
    path: '/core/loaders/usegltf',
    component: UseGLTFDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useKTX2',
    category: 'Loaders',
    title: 'useKTX2',
    description: 'Load compressed KTX2 textures.',
    path: '/core/loaders/usektx2',
    component: UseKTX2Demo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useProgress',
    category: 'Loaders',
    title: 'useProgress',
    description: 'Track asset loading progress.',
    path: '/core/loaders/useprogress',
    component: UseProgressDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useSpriteLoader',
    category: 'Loaders',
    title: 'useSpriteLoader',
    description: 'Load sprite textures.',
    path: '/core/loaders/usespriteloader',
    component: UseSpriteLoaderDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useTexture',
    category: 'Loaders',
    title: 'useTexture',
    description: 'Load image textures.',
    path: '/core/loaders/usetexture',
    component: UseTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'VideoTexture',
    category: 'Loaders',
    title: 'Video Texture',
    description: 'Use video as texture.',
    path: '/core/loaders/videotexture',
    component: VideoTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'WebcamVideoTexture',
    category: 'Loaders',
    title: 'Webcam Video Texture',
    description: 'Use webcam feed as texture.',
    path: '/core/loaders/webcamvideotexture',
    component: WebcamVideoTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Performance ==============================
  {
    name: 'AdaptiveDpr',
    category: 'Performance',
    title: 'Adaptive DPR',
    description: 'Automatically adjust pixel ratio based on performance.',
    path: '/core/performance/adaptivedpr',
    component: AdaptiveDprDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'AdaptiveEvents',
    category: 'Performance',
    title: 'Adaptive Events',
    description: 'Throttle event handling based on performance.',
    path: '/core/performance/adaptiveevents',
    component: AdaptiveEventsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'DetectGPU',
    category: 'Performance',
    title: 'Detect GPU',
    description: 'Detect GPU tier and capabilities.',
    path: '/core/performance/detectgpu',
    component: DetectGPUDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'meshBounds',
    category: 'Performance',
    title: 'Mesh Bounds',
    description: 'Faster raycasting using bounding boxes.',
    path: '/core/performance/meshbounds',
    component: MeshBoundsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'PerformanceMonitor',
    category: 'Performance',
    title: 'Performance Monitor',
    description: 'Monitor and react to performance changes.',
    path: '/core/performance/performancemonitor',
    component: PerformanceMonitorDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Stats',
    category: 'Performance',
    title: 'Stats',
    description: 'Display FPS and performance stats.',
    path: '/core/performance/stats',
    component: StatsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'StatsGl',
    category: 'Performance',
    title: 'Stats GL',
    description: 'WebGL-specific performance stats.',
    path: '/core/performance/statsgl',
    component: StatsGlDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Portal ==============================
  {
    name: 'Fisheye',
    category: 'Portal',
    title: 'Fisheye',
    description: 'Fisheye camera effect.',
    path: '/core/portal/fisheye',
    component: FisheyeDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Hud',
    category: 'Portal',
    title: 'HUD',
    description: 'Heads-up display overlay.',
    path: '/portal/hud',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'Mask',
    category: 'Portal',
    title: 'Mask',
    description: 'Stencil masking for selective rendering.',
    path: '/core/portal/mask',
    component: MaskDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'RenderCubeTexture',
    category: 'Portal',
    title: 'Render Cube Texture',
    description: 'Render scene to cube texture.',
    path: '/portal/rendercubetexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'RenderTexture',
    category: 'Portal',
    title: 'Render Texture',
    description: 'Render scene to texture.',
    path: '/core/portal/rendertexture',
    component: RenderTextureDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Needs WebGPU render target support',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'View',
    category: 'Portal',
    title: 'View',
    description: 'Multiple viewport rendering.',
    path: '/core/portal/view',
    component: ViewDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Staging ==============================
  {
    name: 'Backdrop',
    category: 'Staging',
    title: 'Backdrop',
    description: 'Curved backdrop plane for staging.',
    path: '/core/staging/backdrop',
    component: BackdropDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'BBAnchor',
    category: 'Staging',
    title: 'BB Anchor',
    description: 'Position elements relative to bounding box.',
    path: '/core/staging/bbanchor',
    component: BBAnchorDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Bounds',
    category: 'Staging',
    title: 'Bounds',
    description: 'Fit camera to object bounds.',
    path: '/core/staging/bounds',
    component: BoundsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Center',
    category: 'Staging',
    title: 'Center',
    description: 'Center geometry at origin.',
    path: '/core/staging/center',
    component: CenterDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Environment',
    category: 'Staging',
    title: 'Environment',
    description: 'Environment maps and lighting.',
    path: '/core/staging/environment',
    component: EnvironmentDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Float',
    category: 'Staging',
    title: 'Float',
    description: 'Floating animation effect.',
    path: '/core/staging/float',
    component: FloatDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Grid',
    category: 'Staging',
    title: 'Grid',
    description: 'Infinite grid helper.',
    path: '/core/staging/grid',
    component: GridDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Lightformer',
    category: 'Staging',
    title: 'Lightformer',
    description: 'Shaped area lights for staging.',
    path: '/core/staging/lightformer',
    component: LightformerDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Resize',
    category: 'Staging',
    title: 'Resize',
    description: 'Responsive resizing container.',
    path: '/core/staging/resize',
    component: ResizeDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'ScreenSizer',
    category: 'Staging',
    title: 'Screen Sizer',
    description: 'Scale based on screen size.',
    path: '/core/staging/screensizer',
    component: ScreenSizerDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Shadow',
    category: 'Staging',
    title: 'Shadow',
    description: 'Contact shadow effects.',
    path: '/core/staging/shadow',
    component: ShadowDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Sky',
    category: 'Staging',
    title: 'Sky',
    description: 'Procedural sky shader.',
    path: '/core/staging/sky',
    component: SkyDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'SpotLight',
    category: 'Staging',
    title: 'SpotLight',
    description: 'Enhanced spotlight with volumetric effects.',
    path: '/core/staging/spotlight',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Stage',
    category: 'Staging',
    title: 'Stage',
    description: 'Auto-staging with lights and shadows.',
    path: '/core/staging/stage',
    component: StageDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Stars',
    category: 'Staging',
    title: 'Stars',
    description: 'Procedural starfield.',
    path: '/core/staging/stars',
    component: StarsDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useBoxProjectedEnv',
    category: 'Staging',
    title: 'useBoxProjectedEnv',
    description: 'Box-projected environment maps.',
    path: '/core/staging/useboxprojectedenv',
    component: UseBoxProjectedEnvDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useEnvironment',
    category: 'Staging',
    title: 'useEnvironment',
    description: 'Hook for loading environment maps.',
    path: '/core/staging/useenvironment',
    component: UseEnvironmentDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* UI ==============================
  {
    name: 'useAspect',
    category: 'UI',
    title: 'useAspect',
    description: 'Maintain aspect ratio scaling.',
    path: '/core/ui/useaspect',
    component: UseAspectDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useCursor',
    category: 'UI',
    title: 'useCursor',
    description: 'Change cursor on hover interactions.',
    path: '/core/ui/usecursor',
    component: UseCursorDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'useIntersect',
    category: 'UI',
    title: 'useIntersect',
    description: 'Detect when objects intersect viewport.',
    path: '/core/ui/useintersect',
    component: UseIntersectDemo,
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Materials (Dual renderer - need both legacy and WebGPU) ==============================
  {
    name: 'AccumulativeShadows',
    category: 'Materials',
    title: 'Accumulative Shadows',
    description: 'Soft accumulative shadow ground.',
    path: '/materials/accumulativeshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority for WebGPU',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'BakeShadows',
    category: 'Materials',
    title: 'Bake Shadows',
    description: 'Bake shadows to texture.',
    path: '/materials/bakeshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'BlurPass',
    category: 'Materials',
    title: 'Blur Pass',
    description: 'Gaussian blur post-processing.',
    path: '/materials/blurpass',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'Caustics',
    category: 'Materials',
    title: 'Caustics',
    description: 'Light caustics effect.',
    path: '/materials/caustics',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority for WebGPU',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'ContactShadows',
    category: 'Materials',
    title: 'Contact Shadows',
    description: 'Soft contact shadows.',
    path: '/materials/contactshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority for WebGPU',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'ConvolutionMaterial',
    category: 'Materials',
    title: 'Convolution Material',
    description: 'Convolution blur material.',
    path: '/materials/convolutionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'DiscardMaterial',
    category: 'Materials',
    title: 'Discard Material',
    description: 'Material that discards all fragments.',
    path: '/materials/discardmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'GradientTexture',
    category: 'Materials',
    title: 'Gradient Texture',
    description: 'Procedural gradient texture.',
    path: '/materials/gradienttexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'Image',
    category: 'Materials',
    title: 'Image',
    description: 'Image plane with shader effects.',
    path: '/materials/image',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshDiscardMaterial',
    category: 'Materials',
    title: 'Mesh Discard Material',
    description: 'Material that discards mesh fragments.',
    path: '/materials/meshdiscardmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshDistortMaterial',
    category: 'Materials',
    title: 'Mesh Distort Material',
    description: 'Noise-based vertex distortion.',
    path: '/materials/meshdistortmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshPortalMaterial',
    category: 'Materials',
    title: 'Mesh Portal Material',
    description: 'Portal effect through mesh.',
    path: '/materials/meshportalmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshReflectorMaterial',
    category: 'Materials',
    title: 'Mesh Reflector Material',
    description: 'Planar reflections.',
    path: '/materials/meshreflectormaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshRefractionMaterial',
    category: 'Materials',
    title: 'Mesh Refraction Material',
    description: 'Refraction through glass-like materials.',
    path: '/materials/meshrefractionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshTransmissionMaterial',
    category: 'Materials',
    title: 'Mesh Transmission Material',
    description: 'Glass-like transmission material.',
    path: '/materials/meshtransmissionmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'High priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'MeshWobbleMaterial',
    category: 'Materials',
    title: 'Mesh Wobble Material',
    description: 'Wobbly animated material.',
    path: '/materials/meshwobblematerial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'Outlines',
    category: 'Materials',
    title: 'Outlines',
    description: 'Mesh outline effect.',
    path: '/materials/outlines',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'shaderMaterial',
    category: 'Materials',
    title: 'Shader Material',
    description: 'Custom shader material factory.',
    path: '/materials/shadermaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'High priority - core utility',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'SoftShadows',
    category: 'Materials',
    title: 'Soft Shadows',
    description: 'Percentage closer soft shadows.',
    path: '/materials/softshadows',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'SpotLightMaterial',
    category: 'Materials',
    title: 'SpotLight Material',
    description: 'Volumetric spotlight material.',
    path: '/materials/spotlightmaterial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Medium priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },
  {
    name: 'WireframeMaterial',
    category: 'Materials',
    title: 'Wireframe Material',
    description: 'Stylized wireframe material.',
    path: '/materials/wireframematerial',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Low priority',
    rendererSupport: 'dual',
    legacyStatus: '🟢',
    webgpuStatus: '🔴',
    tslConversion: '🔴',
  },

  //* External ==============================
  {
    name: 'Bvh',
    category: 'External',
    title: 'BVH',
    description: 'Bounding Volume Hierarchy for fast raycasting.',
    path: '/external/bvh',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'CameraControls',
    category: 'External',
    title: 'Camera Controls',
    description: 'Advanced camera controls library.',
    path: '/external/cameracontrols',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Facemesh',
    category: 'External',
    title: 'Facemesh',
    description: 'MediaPipe face mesh integration.',
    path: '/external/facemesh',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'FaceLandmarker',
    category: 'External',
    title: 'Face Landmarker',
    description: 'MediaPipe face landmark detection.',
    path: '/external/facelandmarker',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'NormalTexture',
    category: 'External',
    title: 'Normal Texture',
    description: 'Generate normal maps from images.',
    path: '/external/normaltexture',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },
  {
    name: 'Splat',
    category: 'External',
    title: 'Splat',
    description: 'Gaussian splatting renderer.',
    path: '/external/splat',
    structure: '🟢',
    imports: '🟢',
    types: '🟢',
    tests: '🔴',
    notes: '',
    rendererSupport: 'universal',
  },

  //* Experimental ==============================
  {
    name: 'MarchingCubes',
    category: 'Experimental',
    title: 'Marching Cubes',
    description: 'Marching cubes isosurface extraction.',
    path: '/experimental/marchingcubes',
    structure: '🟢',
    imports: '🟢',
    types: '🟡',
    tests: '🔴',
    notes: 'Utils import, type issues',
    rendererSupport: 'universal',
  },
]

//* Helper Functions ==============================

// Get all components that have working demos
export const getDemos = () => components.filter((c) => c.component !== undefined)

// Get component by name (for ExampleCard, etc.)
export const getComponent = (name: string) => {
  const component = components.find((c) => c.name === name)
  if (!component) throw new Error(`Component ${name} not found`)
  return component
}

// Alias for backward compatibility
export const getMetadata = getComponent

// Check if a component has a demo
export const hasDemo = (name: string) => {
  const component = components.find((c) => c.name === name)
  return component?.component !== undefined
}

// Get components by category
export const getByCategory = (category: Category) => components.filter((c) => c.category === category)

// Get components by renderer support type
export const getByRendererSupport = (support: RendererSupport) =>
  components.filter((c) => c.rendererSupport === support)

// Get components needing WebGPU work
export const getWebGPUTodo = () =>
  components.filter(
    (c) => (c.rendererSupport === 'dual' || c.rendererSupport === 'legacy-only') && c.webgpuStatus !== '🟢'
  )

// Derive tier from category for backward compatibility with sidebar
export const getTier = (c: DreiComponent): Tier => {
  if (c.category === 'External') return 'external'
  if (c.category === 'Experimental') return 'experimental'
  return 'core'
}

// Backward compatibility: Demo type alias
export type Demo = DreiComponent & { component: React.ComponentType }

// Backward compatibility: demos array (only components with demos)
export const demos = getDemos() as Demo[]
