name: Package Size Report

on:
  pull_request: {}

# Only needs read access + PR comment permission
permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pkg-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - uses: pkg-size/action@v1
        with:
          build-command: corepack enable && yarn install && yarn build
          display-size: uncompressed,gzip
          unchanged-files: collapse
          sort-by: delta
          sort-order: desc
          hide-files: '{.yarn/**,node_modules/**}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
